spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: images

upload:
  path: /data/images
  url: https://images.caoyuqian.cn